#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  wheel1,         sensorDigitalIn)
#pragma config(Sensor, dgtl3,  wheel2,         sensorSONAR_cm)
#pragma config(Sensor, dgtl11, ,               sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           big,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           intake,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lf,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           lb,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           rf,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           rb,            tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task flip(){
	if(vexRT[Btn6U]){
		motor[claw] = 300;
		delay(100);
		motor[claw]= -50;
		delay(100);
		motor[claw] = 0;
	}
}

task ball_intake(){
	if(vexRT[Btn6D]){
		motor[intake] = 300;
	}
}

task turn(){
	if(vexRT[Btn5U]){
			motor[big] = 150;
			delay(100);
			motor[big] = 0;
	}
}

task drive(){
	while(1){
		motor[lf] = vexRT[Ch3];
		motor[lb] = vexRT[Ch3];
		motor[rf] = vexRT[Ch2];
		motor[rb] = vexRT[Ch2];
	}
}

task main(){
	startTask(drive);
	int y = 1;
	while(1) y = 0;
}
