#pragma config(Sensor, dgtl2,  tch2,           sensorDigitalIn)
#pragma config(Sensor, dgtl3,  DistT,          sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  winchEncT,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, cplt_tch,       sensorTouch)
#pragma config(Motor,  port2,           winch,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lf,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           lb,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           rb,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rf,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           flipper,       tmotorVex393_MC29, openLoop, reversed) //is it supposed to be reversed?
#pragma config(Motor,  port8,           hold,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//aut1	
	motor[lf] =  motor[lb] = 127;
	motor[rf] = motor[rb] = -127;
	delay(5000);
	motor[lf] =  motor[lb] = -127;
	motor[rf] = motor[rb] = 127;
	delay(5000);
	motor[lf] =  motor[lb] = 0;
	motor[rf] = motor[rb] = 0;
	//aut2
	/*motor[lf] =  motor[lb] = 127;
	motor[rf] = motor[rb] = -127;
	delay(3000);
	motor[lf] =  motor[lb] = 0;
	motor[rf] = motor[rb] = 0;
	motor[flipper] = 127;
	delay(3000);
	motor[flipper] = 0;
	motor[lf] =  motor[lb] = -127;
	motor[rf] = motor[rb] = 127;
	delay(3000);
	motor[lf] =  motor[lb] = 0;
	otor[rf] = motor[rb] = 0;*/
}

/*---------------------------------------------------------------------------*/
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
int z = 1;
task flip(){
	while(1){
		if(vexRT[Btn6U]){
			motor[flipper] = 127; //Moving the motors for the flipper
			delay(750); //delay 100
			motor[flipper] = 0; //The motor flipper power is now 0.
		}else if(vexRT[Btn6D]){
			motor[flipper] = -127;
			delay(400);
			motor[flipper] = 0;
		}
	}
}

task take(){ //Taking in the ball
	while(1){
		if(vexRT[Btn7U]){ //This checks if the button Btn7U is pressed
			if(z == 1){ //Checks if z is 1
				motor[intake] = -100;
				z = 0; //Changes z to 0.
			}
			else{ //If z is not 1
				motor[intake] = 0;
				z = 1;
			}
			delay(250);
		}
	}
}

task throw(){
	int orig;
	int state = 0;
	for(;;){
		if(vexRT[Btn8D]){
			orig = SensorValue(winchEncT);
			while(SensorValue(winchEncT) > -1300) motor[winch] = -70;
				delay(1000);
				motor[hold] = 100;
				delay(1000);
				motor[winch] = 0;
				motor[hold] = 0;
			while(SensorValue(winchEncT) != orig) motor[winch] = 70;
				motor[winch] = 0;
		}
		if(vexRT(Btn8U)){
			motor[hold] = -100;
		}else motor[hold] = 0;
	}
}

task drive(){ //This drives the robot
	while(1){
		motor[lf] = vexRT[Ch3];
		motor[lb] = vexRT[Ch3];
		motor[rf] = -vexRT[Ch2];
		motor[rb] = -vexRT[Ch2];
	}
}

task usercontrol(){
  // User control code here, inside the loop
	startTask(drive); //This starts the drive tasks
	startTask(flip); //This starts the flip task
	startTask(throw); //This starts the throw task
	startTask(take); //This starts the intake task
	int y = 1;
	while(1) y++;
}


